# Config version, don't edit
version: 4

# Damage Indicator options, here you can define in what type of entities we
# should show the damage indicators and completely disable this feature.
Damage Indicator:
  Enabled: true
  Player: true
  Monster: true
  Animals: true
  # Use %health% for the regain health you get
  # Use %damage% for the damage you get
  Format:
    EntityRegain: '&7+&a%health%'
    EntityDamage: '&7-&c%damage%'
    # Here you define the decimal format for the damage and health
    # See https://docs.oracle.com/javase/8/docs/api/java/text/DecimalFormat.html
    # for more information.
    Decimal: '#.##'
  # Distance in Y axis from the entity where we should spawn the damage indicator
  # A distance of 2 is recommended for 1.8 servers
  Distance: 1.6
  # List of disabled entity types that shouldn't spawn damage indicators
  # See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  # for all possible entities.
  # If you don't want to disable entities, remove elements from the list set it to
  # Disabled Entities: []
  Disabled Entities: []

  # List of spawn reasons that we must listen and mark entities, so they won't spawn
  # damage indicators.
  # See https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # for all possible spawn reasons.
  # If you don't want to disable for spawn reasons, remove elements from the list set it to
  # Disabled Spawn Reasons: []
  Disabled Spawn Reasons:
    - SPAWNER
  # List of damage causes that we must ignore for damage indicators.
  # See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
  # for all possible damage causes.
  # If you don't want to disable for damage causes, remove elements from the list set it to
  # Disabled Damage Causes: []
  Disabled Damage Causes:
    - SUICIDE
  # Enable or disable damage indicators for players who are sneaking, it is recommended to disable for PvP servers.
  # true: damage indicators are shown even if you're sneaking.
  # false: damage indicators aren't shown when you're sneaking.
  Sneaking: false

# Blood options, here you can configure this feature.
Blood:
  Enabled: true
  Player: true
  Monster: true
  Animals: true
  # List of disabled entity types that shouldn't bleed.
  # See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  # for all possible entities.
  # If you don't want to disable entities, remove elements from the list set it to
  # Disabled Entities: []
  Disabled Entities: []

  # List of spawn reasons that we must listen and mark entities, so they won't bleed.
  # See https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # for all possible spawn reasons.
  # If you don't want to disable for spawn reasons, remove elements from the list set it to
  # Disabled Spawn Reasons: []
  Disabled Spawn Reasons:
    - SPAWNER
  # List of damage causes that we must ignore for blood.
  # See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
  # for all possible damage causes.
  # If you don't want to disable for damage causes, remove elements from the list set it to
  # Disabled Damage Causes: []
  Disabled Damage Causes:
    - DROWNING
  # Enable or disable blood particles for players who are sneaking.
  # true: blood particles are shown even if you're sneaking.
  # false: blood particles aren't shown when you're sneaking.
  Sneaking: true

Messages:
  Damage Indicator:
    Enabled: '&7Your damage indicator show status has changed to: &aenabled'
    Disabled: '&7Your damage indicator show status has changed to: &cdisabled'
