name: GlovedPlugin
version: '0.0.1'
main: Gloves.glovedplugin
softdepend:  [ ProtocolLib, HolographicDisplays, PlaceholderAPI ]
api-version: 1.19
commands:
  menu:
    description: Custom menu for Commands
    usage: /menu
  damageindicator:
    description: edit damageindicator settings
    usage: /<command> <arguments>
    aliases: di