name: GlovedPlugin
version: '0.0.1'
main: Gloves.glovedplugin
api-version: 1.19
commands:
  fly:
    description: Toggles flying for the command sender.
    usage: /fly
    aliases: f
    permission: fly
    permission-message: You do not have permission.
  menu:
    description: Opens a custom menu
    usage: /menu
